// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"demo/app/login/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: loginHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.LogTest},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/",
					Handler: HomeHandler(serverCtx),
				},
			}...,
		),
	)
}
