// Code generated by goctl. DO NOT EDIT.
package types

type ListReq struct {
	Pager
}

type ListResp struct {
	List  interface{} `json:"list"`
	Total uint64      `json:"total"`
}

type CreateReq struct {
}

type CreateResp struct {
}

type UpdateReq struct {
}

type UpdateResp struct {
}

type DeleteReq struct {
}

type DeleteResp struct {
}

type Pager struct {
	Page     int                    `json:"page,range=[0:),default=1,optional"`
	Size     int                    `json:"size,range=(:500],default=10,optional"`
	OrderKey string                 `json:"order_key,optional"`                // 排序字段
	Order    string                 `json:"order,options=[desc,asc],optional"` // 排序逻辑
	Where    map[string]interface{} `json:"where,optional"`
}

type DbQueryListResponse struct {
	Total int64       `json:"total"`
	List  interface{} `json:"list"`
}
