// Code generated by gen. DO NOT EDIT.
package query_mng

import (
	"content_svr/app/maozhua_admin_svr/common/db"
	"content_svr/db/mongodb/model"
)

type QueryMng struct {
    {{range .}}{{.Type}}   model.{{.Type}}Model
    {{end}}
}

func NewQueryMng(monCfg db.MongoConfig) *QueryMng {
	return &QueryMng{
        {{range .}}{{.Type}}:  model.New{{.Type}}Model(monCfg),
        {{end}}
	}
}
