// Code generated by goctl. DO NOT EDIT.
// Source: login.proto

package login_client

import (
	"context"

	"demo/app/login/rpc/pb/login"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AuthReq   = login.AuthReq
	AuthResp  = login.AuthResp
	LoginReq  = login.LoginReq
	LoginResp = login.LoginResp

	Login interface {
		Auth(ctx context.Context, in *AuthReq, opts ...grpc.CallOption) (*AuthResp, error)
		Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
	}

	defaultLogin struct {
		cli zrpc.Client
	}
)

func NewLogin(cli zrpc.Client) Login {
	return &defaultLogin{
		cli: cli,
	}
}

func (m *defaultLogin) Auth(ctx context.Context, in *AuthReq, opts ...grpc.CallOption) (*AuthResp, error) {
	client := login.NewLoginClient(m.cli.Conn())
	return client.Auth(ctx, in, opts...)
}

func (m *defaultLogin) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := login.NewLoginClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}
